//! Preview provider availability — `{nc:}has-preview` (§10.12 / §11.1).
//!
//! Mirrors PHP `PreviewManager::isAvailable()` (`lib/private/PreviewManager.php`),
//! which reports `true` iff **some registered provider** matches the file's
//! mimetype.  A provider is registered only when:
//!
//! 1. its class is in `enabledPreviewProviders` (the system array; when unset
//!    PHP's **default** set applies — `getEnabledDefaultProvider`, `:260-290`), and
//! 2. its per-provider availability holds — a binary on disk (ffmpeg / LibreOffice)
//!    or, for the imagick family, the imagick extension supporting the format.
//!
//! ## Resolved model ([`ProviderRegistry`])
//!
//! | Category | Mimetypes | Gate |
//! |----------|-----------|------|
//! | GD images | `image/png`, `image/jpeg`, `image/gif`, `image/bmp`, `image/x-xbitmap`, `image/webp` | class in enabled list |
//! | Krita | `application/x-krita` | class in enabled list |
//! | Text | `text/plain` (TXT), `text/markdown`+`text/x-markdown` (MarkDown) | class in enabled list |
//! | MP3 | `audio/mpeg` | class in enabled list (NOT in PHP default) |
//! | OpenDocument | `application/vnd.oasis.opendocument.*` | class in enabled list — **no binary** (`OpenDocument extends Bundled`; extracts the ODF-embedded `Thumbnails/thumbnail.png`) |
//! | Video | `video/*` | `Movie` in list **and** ffmpeg binary |
//! | MS Office | `application/msword`, `application/vnd.ms-*`, `application/vnd.openxmlformats-officedocument.*`, `application/vnd.sun.xml.*`, `image/emf` | per-class in list **and** LibreOffice binary |
//! | Imaginary raster set | `image/{bmp,x-bitmap,png,jpeg,gif,heic,heif,svg+xml,tiff,webp}`, `application/illustrator` | Imaginary backend available (URL configured **and** `OC\Preview\Imaginary` in list) |
//! | imagick family | `image/svg+xml`, `image/tiff`, `image/{heic,heif,tga,sgi}`(+`x-`variants), `application/{pdf,illustrator,x-photoshop,postscript,font-sfnt,x-font}` | class in enabled list **and** format supported by PHP's imagick (startup probe); Imaginary additionally covers svg/tiff/heic/heif/illustrator |
//!
//! ## imagick introspection (startup probe)
//!
//! The imagick-backed providers (SVG, TIFF, PDF, Illustrator, Photoshop,
//! Postscript, Font, HEIC, TGA, SGI) are registered in PHP only when the class is
//! enabled **and** the PHP imagick build supports the format
//! (`IMagickSupport::supportsFormat($f) === count(queryFormats($f)) === 1`).  Rust
//! replicates this by probing the PHP build **once at startup** (a single `php -r`
//! call — the same interpreter already used to parse `config.php`) for which of
//! [`IMAGICK_PROBE_FORMATS`] imagick supports, then gating each provider on
//! class-membership **and** that result.  This makes `{nc:}has-preview` faithful on
//! imagick installs — e.g. existing HEIC previews generated by PHP's imagick HEIC
//! delegate are still *requested* by the web gallery even when Imaginary is absent.
//! If `php` is unavailable or the probe fails, imagick is treated as absent (safe
//! under-report).  Note the probe affects the `has-preview` **hint** only: native
//! *generation* (11.4) stays Imaginary-only, so an imagick-only miss still proxies
//! to PHP-FPM (which generates via imagick) — behaviour is never worse than today.
//!
//! ## Deviations from PHP (documented per CLAUDE.md)
//!
//! - **imagick support is snapshotted at startup.** If the PHP imagick build's
//!   format support changes after the server starts (extension install/removal),
//!   the registry is stale until restart. Acceptable: imagick format support is a
//!   deploy-time property, and the failure mode is a stale hint, never wrong content.
//! - **Imaginary availability also requires a valid URL.** PHP registers Imaginary
//!   on list-membership alone and only errors on the URL at generation time; gating
//!   `has-preview` on URL+list upholds the invariant `has-preview ⇒ generatable`
//!   (avoids `has-preview=true` followed by a generation 404 — the failure mode
//!   §11.1 exists to prevent).
//! - **`enabledPreviewProviders` replaces the default set** (not additive) — exactly
//!   PHP's `getSystemValue(key, default)`. Setting it to `[OC\Preview\Movie]`
//!   disables the default image providers. Only listing the abstract `OC\Preview\Image`
//!   re-expands to all GD image providers (PHP's `Image::class` special case).
//! - **Empty binary path = not configured.** PHP's `is_string('')` would register a
//!   provider with a useless empty binary; Rust treats `''` as unset and falls through
//!   to the `$PATH` search (matches intent; the previous Rust behaviour and tests).
//! - **Config class values are trimmed of a leading `\`** before membership checks
//!   (PHP compares untrimmed). A lenient robustness measure that can only enable a
//!   provider the operator clearly intended.
//! - **PATH search only.** Binary resolution uses the config path or a `$PATH` search
//!   (PHP `binaryFinder->findBinaryPath`); PHP's additional hardcoded common-install
//!   directory list is not replicated (under-reports only).
//! - **External-storage `previews` mount option** is not yet wired (no external
//!   storage support); home storage has no mount and PHP defaults the option `true`.

use std::collections::HashSet;

// ── Provider class names (`PreviewManager` `use` imports, `:12-47`) ────────────
const P_MARKDOWN: &str = "OC\\Preview\\MarkDown";
const P_TXT: &str = "OC\\Preview\\TXT";
const P_OPENDOCUMENT: &str = "OC\\Preview\\OpenDocument";
const P_PNG: &str = "OC\\Preview\\PNG";
const P_JPEG: &str = "OC\\Preview\\JPEG";
const P_GIF: &str = "OC\\Preview\\GIF";
const P_BMP: &str = "OC\\Preview\\BMP";
const P_XBITMAP: &str = "OC\\Preview\\XBitmap";
const P_WEBP: &str = "OC\\Preview\\WebP";
const P_KRITA: &str = "OC\\Preview\\Krita";
const P_MP3: &str = "OC\\Preview\\MP3";
/// Abstract base — listing it expands to all GD image providers (PHP `:281-283`).
const P_IMAGE: &str = "OC\\Preview\\Image";
const P_MOVIE: &str = "OC\\Preview\\Movie";
const P_MSOFFICEDOC: &str = "OC\\Preview\\MSOfficeDoc";
const P_MSOFFICE2003: &str = "OC\\Preview\\MSOffice2003";
const P_MSOFFICE2007: &str = "OC\\Preview\\MSOffice2007";
const P_STAROFFICE: &str = "OC\\Preview\\StarOffice";
const P_EMF: &str = "OC\\Preview\\EMF";
const P_IMAGINARY: &str = "OC\\Preview\\Imaginary";
// imagick-backed providers (registered only when the class is enabled *and* the
// PHP imagick build supports the format — `PreviewManager.php:325-348`).
const P_SVG: &str = "OC\\Preview\\SVG";
const P_TIFF: &str = "OC\\Preview\\TIFF";
const P_PDF: &str = "OC\\Preview\\PDF";
const P_ILLUSTRATOR: &str = "OC\\Preview\\Illustrator";
const P_PHOTOSHOP: &str = "OC\\Preview\\Photoshop";
const P_POSTSCRIPT: &str = "OC\\Preview\\Postscript";
const P_FONT: &str = "OC\\Preview\\Font";
const P_HEIC: &str = "OC\\Preview\\HEIC";
const P_TGA: &str = "OC\\Preview\\TGA";
const P_SGI: &str = "OC\\Preview\\SGI";

/// The imagick query-formats probed from the PHP build at startup, in PHP's
/// `supportsFormat` terms (`PreviewManager.php:325-348` query-format keys).
const IMAGICK_PROBE_FORMATS: &[&str] = &[
    "SVG", "TIFF", "PDF", "AI", "PSD", "EPS", "TTF", "HEIC", "TGA", "SGI",
];

/// Imaginary's exact supported mimetype set (`Imaginary::supportedMimeTypes():44-46`).
///
/// **One source of truth** shared by `{nc:}has-preview` (this module) and native
/// generation (11.4): a mimetype here is Rust-generatable exactly when the Imaginary
/// backend is available.  Note `image/x-bitmap` (Imaginary) is distinct from the GD
/// provider's `image/x-xbitmap` (XBitmap) — different mimetypes, different providers.
pub const IMAGINARY_MIMES: &[&str] = &[
    "image/bmp",
    "image/x-bitmap",
    "image/png",
    "image/jpeg",
    "image/gif",
    "image/heic",
    "image/heif",
    "image/svg+xml",
    "image/tiff",
    "image/webp",
    "application/illustrator",
];

/// Resolved preview-provider gating, built **once** at startup from system config.
///
/// Single source of truth for `{nc:}has-preview` (§11.1) and, later, native
/// generation (11.4) — keeping the property and the generator from ever disagreeing
/// (`rust_generatable(m) ⇒ is_available(m)`).
#[derive(Clone)]
pub struct ProviderRegistry {
    enable_previews: bool,
    /// Enabled provider classes — PHP default applied when the config key is unset,
    /// `Image` base-class expansion applied.  Membership mirrors PHP's
    /// `in_array(trim(class,'\\'), enabled)`.
    enabled: HashSet<String>,
    /// `Movie` provider usable: `preview_ffmpeg_path` set or ffmpeg found on `$PATH`.
    ffmpeg: bool,
    /// MS-Office family usable: `preview_libreoffice_path` set or a LibreOffice /
    /// OpenOffice binary found on `$PATH`.
    libreoffice: bool,
    /// Imaginary backend usable: `preview_imaginary_url` valid **and**
    /// `OC\Preview\Imaginary` in the enabled list.
    imaginary: bool,
    /// Imagick query-formats (uppercase) supported by the PHP imagick build,
    /// detected once at startup by [`detect_imagick_formats`].  Empty when imagick
    /// is absent or the probe failed — which disables the imagick-family providers
    /// (a safe under-report).
    imagick_formats: HashSet<String>,
}

impl ProviderRegistry {
    /// Build from system config, resolving binary availability (config-then-`$PATH`)
    /// and probing the PHP imagick build for supported formats.  Intended to be
    /// called once at startup and shared behind an `Arc`.
    pub fn from_config(cfg: &nc_db::config::NcConfig) -> Self {
        let ffmpeg = resolve_binary(cfg.preview_ffmpeg_path.as_deref(), &["ffmpeg"]);
        let libreoffice = resolve_binary(
            cfg.preview_libreoffice_path.as_deref(),
            &["libreoffice", "soffice", "openoffice"],
        );
        let imagick = detect_imagick_formats(&nc_db::config::resolve_php_binary(
            cfg.php_binary.as_deref(),
        ));
        Self::build(
            cfg.enable_previews,
            cfg.enabled_preview_providers.as_deref(),
            ffmpeg,
            libreoffice,
            imaginary_url_valid(cfg.preview_imaginary_url.as_ref().map(|s| s.expose())),
            &imagick.iter().map(|s| s.as_str()).collect::<Vec<_>>(),
        )
    }

    /// Pure constructor — no `$PATH` search, no `php` probe.  Used by tests and
    /// [`Self::from_config`].  `imagick_formats` are the uppercase query-formats the
    /// PHP imagick build supports (see [`detect_imagick_formats`]).
    pub fn build(
        enable_previews: bool,
        enabled_providers: Option<&[String]>,
        ffmpeg: bool,
        libreoffice: bool,
        imaginary_url_valid: bool,
        imagick_formats: &[&str],
    ) -> Self {
        let enabled = resolve_enabled(enabled_providers);
        let imaginary = imaginary_url_valid && enabled.contains(P_IMAGINARY);
        let imagick_formats = imagick_formats
            .iter()
            .map(|s| s.to_ascii_uppercase())
            .collect();
        Self {
            enable_previews,
            enabled,
            ffmpeg,
            libreoffice,
            imaginary,
            imagick_formats,
        }
    }

    /// Global `enable_previews` system config (default `true`).  When `false`, PHP
    /// throws `NotFoundException('Previews disabled')` → the routes return `404`.
    pub fn enable_previews(&self) -> bool {
        self.enable_previews
    }

    /// Whether the Imaginary backend is usable for native generation (11.4).
    pub fn imaginary_available(&self) -> bool {
        self.imaginary
    }

    /// Can *Rust* generate this mimetype natively?  Strict subset of
    /// [`Self::is_available`]: the Imaginary-supported raster set when the backend
    /// is up.  Drives the 11.4 miss-path decision (else PHP-FPM fallback).
    pub fn rust_generatable(&self, mime: &str) -> bool {
        if !self.enable_previews || !self.imaginary {
            return false;
        }
        let mime = mime.split(';').next().unwrap_or(mime).trim();
        IMAGINARY_MIMES.contains(&mime)
    }

    /// PHP `PreviewManager::isAvailable` — `true` iff some registered provider
    /// matches `mime_type`.  Drives the `{nc:}has-preview` PROPFIND property.
    ///
    /// `is_mounted` carries the external-storage mount state; its `previews`
    /// option is not yet wired (PHP defaults it `true`) — see module docs.
    pub fn is_available(&self, mime_type: &str, _is_mounted: bool) -> bool {
        if !self.enable_previews {
            return false;
        }

        // Strip a charset suffix commonly appended to mimetypes
        // (e.g. "text/plain; charset=utf-8" → "text/plain").
        let mime = mime_type.split(';').next().unwrap_or(mime_type).trim();

        // Imaginary registered ⇒ its whole supported set is available, regardless of
        // the individual GD providers (PHP iterates every matching provider and the
        // first available one wins).
        if self.imaginary && IMAGINARY_MIMES.contains(&mime) {
            return true;
        }

        let e = |p: &str| self.enabled.contains(p);
        // imagick format supported by the PHP build (startup probe).
        let im = |fmt: &str| self.imagick_formats.contains(fmt);

        match mime {
            // GD image providers — class membership only.
            "image/png" => e(P_PNG),
            "image/jpeg" => e(P_JPEG),
            "image/gif" => e(P_GIF),
            "image/bmp" => e(P_BMP),
            "image/x-xbitmap" => e(P_XBITMAP),
            "image/webp" => e(P_WEBP),
            "application/x-krita" => e(P_KRITA),

            // Text providers.
            "text/plain" => e(P_TXT),
            "text/markdown" | "text/x-markdown" => e(P_MARKDOWN),

            // MP3 (not in PHP's default provider set).
            "audio/mpeg" | "audio/mp3" => e(P_MP3),

            // OpenDocument extends Bundled — extracts the ODF-embedded thumbnail,
            // needs NO office binary (unlike the MSOffice family below).
            _ if mime.starts_with("application/vnd.oasis.opendocument.") => e(P_OPENDOCUMENT),

            // HEIC/HEIF via the imagick HEIC delegate (PHP regex `/image\/(x-)?hei(f|c)/`).
            // Imaginary, when available, also covers these via the early return above.
            "image/heic" | "image/heif" | "image/x-heic" | "image/x-heif"
            | "image/heic-sequence" | "image/heif-sequence" => e(P_HEIC) && im("HEIC"),

            // Video: Movie provider, gated on the list and the ffmpeg binary.
            _ if mime.starts_with("video/") => e(P_MOVIE) && self.ffmpeg,

            // MS-Office family (extends Office): per-class list gate + LibreOffice.
            "application/msword" => e(P_MSOFFICEDOC) && self.libreoffice,
            "image/emf" => e(P_EMF) && self.libreoffice,
            _ if mime.starts_with("application/vnd.ms-") => e(P_MSOFFICE2003) && self.libreoffice,
            _ if mime.starts_with("application/vnd.openxmlformats-officedocument.") => {
                e(P_MSOFFICE2007) && self.libreoffice
            }
            _ if mime.starts_with("application/vnd.sun.xml.") => {
                e(P_STAROFFICE) && self.libreoffice
            }

            // ── imagick-backed providers ─────────────────────────────────────
            // Registered in PHP only when the class is enabled AND the PHP imagick
            // build supports the format (`supportsFormat` ≡ `queryFormats(f)==1`),
            // detected here via the startup probe.  Imaginary additionally covers
            // svg/tiff/heic/heif/illustrator through the early return above; these
            // arms supply the imagick path (and the formats Imaginary never covers:
            // pdf, photoshop, postscript, font, tga, sgi).
            "image/svg+xml" => e(P_SVG) && im("SVG"),
            "image/tiff" => e(P_TIFF) && im("TIFF"),
            "application/illustrator" => e(P_ILLUSTRATOR) && im("AI"),
            "application/x-photoshop" => e(P_PHOTOSHOP) && im("PSD"),
            "application/postscript" => e(P_POSTSCRIPT) && im("EPS"),
            "application/pdf" => e(P_PDF) && im("PDF"),
            // Font provider regex: `/application\/(?:font-sfnt|x-font$)/` — note this
            // is NOT `font/*` (e.g. `font/ttf` has no PHP provider → false).
            "application/font-sfnt" | "application/x-font" => e(P_FONT) && im("TTF"),
            // TGA: `/image\/(x-)?t(ar)?ga/`
            "image/tga" | "image/x-tga" | "image/targa" | "image/x-targa" => {
                e(P_TGA) && im("TGA")
            }
            // SGI: `/image\/(x-)?sgi/`
            "image/sgi" | "image/x-sgi" => e(P_SGI) && im("SGI"),

            // Everything else has no provider.
            _ => false,
        }
    }
}

/// Resolve the enabled provider set from config, applying PHP's default when unset
/// and the `Image` base-class expansion (`PreviewManager::getEnabledDefaultProvider`).
fn resolve_enabled(configured: Option<&[String]>) -> HashSet<String> {
    let mut set: HashSet<String> = match configured {
        // Config key set → replaces the default set entirely (PHP `getSystemValue`).
        Some(list) => list
            .iter()
            .map(|c| c.trim_start_matches('\\').to_string())
            .collect(),
        // Unset → PHP default: MarkDown, TXT, OpenDocument + the GD image providers.
        None => [
            P_MARKDOWN,
            P_TXT,
            P_OPENDOCUMENT,
            P_PNG,
            P_JPEG,
            P_GIF,
            P_BMP,
            P_XBITMAP,
            P_KRITA,
            P_WEBP,
        ]
        .iter()
        .map(|s| s.to_string())
        .collect(),
    };

    // PHP: listing the abstract `Image` base class expands to all GD image providers.
    if set.contains(P_IMAGE) {
        for p in [P_PNG, P_JPEG, P_GIF, P_BMP, P_XBITMAP, P_KRITA, P_WEBP] {
            set.insert(p.to_string());
        }
    }
    set
}

/// PHP treats the default `'invalid'` and the empty string as "not configured"
/// (`Imaginary::getCroppedThumbnail` logs an error and returns null on `'invalid'`).
fn imaginary_url_valid(url: Option<&str>) -> bool {
    matches!(url, Some(u) if !u.is_empty() && u != "invalid")
}

/// Probe the **PHP** imagick build once for the query-formats it supports,
/// replicating `IMagickSupport::supportsFormat` (`count(queryFormats($f)) === 1`)
/// for each format in [`IMAGICK_PROBE_FORMATS`].  Returns uppercase format names.
///
/// Any failure (interpreter missing, non-zero exit, imagick absent) yields an
/// empty set, which disables the imagick-family providers — a safe under-report
/// (a stale or missing hint degrades to a generic icon, never wrong content;
/// generation of imagick-only types still proxies to PHP-FPM).
fn detect_imagick_formats(php: &str) -> Vec<String> {
    // Build the format list literal for the PHP snippet from the shared constant so
    // the probe and the Rust model can never drift apart.
    let list = IMAGICK_PROBE_FORMATS
        .iter()
        .map(|f| format!("'{f}'"))
        .collect::<Vec<_>>()
        .join(",");
    let script = format!(
        "if (!extension_loaded('imagick')) {{ exit(0); }} \
         try {{ $i = new Imagick(); }} catch (Throwable $e) {{ exit(0); }} \
         foreach ([{list}] as $f) {{ \
             if (count($i->queryFormats($f)) === 1) {{ echo $f, ','; }} \
         }}"
    );
    match std::process::Command::new(php).arg("-r").arg(&script).output() {
        Ok(out) if out.status.success() => {
            parse_imagick_probe(&String::from_utf8_lossy(&out.stdout))
        }
        Ok(out) => {
            tracing::debug!(
                "imagick probe ({php}) exited non-zero; imagick treated as unavailable: {}",
                String::from_utf8_lossy(&out.stderr).trim()
            );
            Vec::new()
        }
        Err(e) => {
            tracing::debug!("imagick probe could not run {php} ({e}); imagick treated as unavailable");
            Vec::new()
        }
    }
}

/// Parse the probe's comma-separated stdout (e.g. `"SVG,TIFF,HEIC,"`) into
/// uppercase format names.  Pure — unit-tested independently of the `php` call.
fn parse_imagick_probe(stdout: &str) -> Vec<String> {
    stdout
        .split(',')
        .map(|s| s.trim().to_ascii_uppercase())
        .filter(|s| !s.is_empty())
        .collect()
}

/// Resolve a preview binary: an explicit (non-empty) config path wins; otherwise
/// search `$PATH`.  Mirrors PHP `binaryFinder->findBinaryPath`.
fn resolve_binary(config_path: Option<&str>, names: &[&str]) -> bool {
    if let Some(p) = config_path {
        if !p.is_empty() {
            return true;
        }
    }
    names.iter().any(|n| on_path(n))
}

fn on_path(name: &str) -> bool {
    let Some(path) = std::env::var_os("PATH") else {
        return false;
    };
    std::env::split_paths(&path).any(|dir| is_executable(&dir.join(name)))
}

#[cfg(unix)]
fn is_executable(p: &std::path::Path) -> bool {
    use std::os::unix::fs::PermissionsExt;
    match std::fs::metadata(p) {
        Ok(m) => m.is_file() && m.permissions().mode() & 0o111 != 0,
        Err(_) => false,
    }
}

#[cfg(not(unix))]
fn is_executable(p: &std::path::Path) -> bool {
    p.is_file()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// PHP's default provider set (class names), used to build "default + extras"
    /// configs — configuring `enabledPreviewProviders` *replaces* the default.
    const DEFAULTS: &[&str] = &[
        P_MARKDOWN,
        P_TXT,
        P_OPENDOCUMENT,
        P_PNG,
        P_JPEG,
        P_GIF,
        P_BMP,
        P_XBITMAP,
        P_KRITA,
        P_WEBP,
    ];

    /// Build a registry.  `providers = None` → PHP default set.  Binaries and the
    /// imagick format set are passed explicitly so tests never touch `$PATH`/`php`.
    fn reg(
        providers: Option<&[&str]>,
        ffmpeg: bool,
        libreoffice: bool,
        imaginary_url: bool,
    ) -> ProviderRegistry {
        reg_i(providers, ffmpeg, libreoffice, imaginary_url, &[])
    }

    /// Like [`reg`] but with an explicit imagick-supported format set.
    fn reg_i(
        providers: Option<&[&str]>,
        ffmpeg: bool,
        libreoffice: bool,
        imaginary_url: bool,
        imagick: &[&str],
    ) -> ProviderRegistry {
        let owned: Option<Vec<String>> =
            providers.map(|v| v.iter().map(|s| s.to_string()).collect());
        ProviderRegistry::build(
            true,
            owned.as_deref(),
            ffmpeg,
            libreoffice,
            imaginary_url,
            imagick,
        )
    }

    fn av(reg: &ProviderRegistry, mime: &str) -> bool {
        reg.is_available(mime, false)
    }

    // ── 11.1: default provider set parity ──────────────────────────────────

    #[test]
    fn default_provider_set_matches_php() {
        // Binaries held available so the ONLY variable under test is the default list.
        let r = reg(None, true, true, false);

        // In PHP's default set → available.
        for m in [
            "image/png",
            "image/jpeg",
            "image/gif",
            "image/bmp",
            "image/webp",
            "image/x-xbitmap",
            "text/plain",
            "text/markdown",
            "text/x-markdown",
            "application/vnd.oasis.opendocument.text",
            "application/vnd.oasis.opendocument.spreadsheet",
            "application/x-krita",
        ] {
            assert!(av(&r, m), "expected available by default: {m}");
        }

        // Not in the default set → unavailable (parity fixes vs the old matrix).
        for m in [
            "video/mp4",           // Movie not in default list (even with ffmpeg)
            "application/pdf",     // imagick/ImaginaryPDF — not introspected / out of scope
            "image/svg+xml",       // imagick-only, no Imaginary here
            "image/tiff",          // imagick-only
            "audio/mpeg",          // MP3 not in default list
            "font/ttf",            // no provider matches font/* (PHP Font is application/font-sfnt|x-font)
            "application/font-sfnt", // Font provider not in default list
            "image/heic",          // imagick HEIC delegate, no Imaginary here
            "application/msword",  // MSOfficeDoc not in default list (even with libreoffice)
            "application/illustrator",
            "application/postscript",
            "application/x-photoshop",
        ] {
            assert!(!av(&r, m), "expected UNavailable by default: {m}");
        }
    }

    #[test]
    fn configured_list_replaces_default() {
        // Setting enabledPreviewProviders REPLACES the default set (PHP getSystemValue).
        let r = reg(Some(&["OC\\Preview\\Movie"]), true, false, false);
        assert!(av(&r, "video/mp4"), "Movie listed + ffmpeg → video available");
        assert!(!av(&r, "image/png"), "default PNG dropped when list is set");
        assert!(!av(&r, "text/plain"), "default TXT dropped when list is set");
    }

    #[test]
    fn enabled_providers_config_extends_set() {
        // Default set + Movie + Imaginary, with ffmpeg + Imaginary URL available.
        let mut providers: Vec<&str> = DEFAULTS.to_vec();
        providers.push("OC\\Preview\\Movie");
        providers.push("OC\\Preview\\Imaginary");
        let r = reg(Some(&providers), true, false, true);

        // Movie now enabled → video available.
        assert!(av(&r, "video/mp4"));
        // Imaginary available → its supported set, incl. heic/heif/svg/tiff/illustrator.
        assert!(av(&r, "image/heic"));
        assert!(av(&r, "image/heif"));
        assert!(av(&r, "image/svg+xml"));
        assert!(av(&r, "image/tiff"));
        assert!(av(&r, "application/illustrator"));
        // Default image providers still enabled.
        assert!(av(&r, "image/png"));
        // Imaginary does NOT cover pdf → still unavailable (PHP-FPM path).
        assert!(!av(&r, "application/pdf"));
    }

    // ── Imaginary gating: requires BOTH a valid URL and list membership ─────

    #[test]
    fn imaginary_gating_requires_url_and_list() {
        // In list but no URL → not available.
        let mut providers: Vec<&str> = DEFAULTS.to_vec();
        providers.push("OC\\Preview\\Imaginary");
        let no_url = reg(Some(&providers), false, false, false);
        assert!(!av(&no_url, "image/heic"));
        assert!(!av(&no_url, "image/svg+xml"));

        // URL set but Imaginary NOT in the list → not available.
        let no_list = reg(None, false, false, true);
        assert!(!av(&no_list, "image/heic"));

        // Both → available.
        let both = reg(Some(&providers), false, false, true);
        assert!(av(&both, "image/heic"));
        assert!(av(&both, "image/heif"));
    }

    #[test]
    fn imaginary_url_invalid_sentinel_is_not_configured() {
        // PHP default 'invalid' and '' mean "not configured".
        assert!(!imaginary_url_valid(None));
        assert!(!imaginary_url_valid(Some("")));
        assert!(!imaginary_url_valid(Some("invalid")));
        assert!(imaginary_url_valid(Some("http://localhost:9090")));
    }

    // ── Image base-class expansion ─────────────────────────────────────────

    #[test]
    fn image_base_class_expansion() {
        // Listing the abstract OC\Preview\Image expands to all GD image providers.
        let r = reg(Some(&["OC\\Preview\\Image"]), false, false, false);
        for m in ["image/png", "image/jpeg", "image/gif", "image/bmp", "image/webp"] {
            assert!(av(&r, m), "Image base class should enable {m}");
        }
        assert!(!av(&r, "text/plain"), "Image expansion must not enable TXT");
    }

    // ── Binary gating: ffmpeg / LibreOffice ────────────────────────────────

    #[test]
    fn video_requires_movie_and_ffmpeg() {
        let mut providers: Vec<&str> = DEFAULTS.to_vec();
        providers.push("OC\\Preview\\Movie");
        assert!(av(&reg(Some(&providers), true, false, false), "video/mp4"));
        assert!(av(&reg(Some(&providers), true, false, false), "video/webm"));
        // Movie listed but no ffmpeg → unavailable.
        assert!(!av(&reg(Some(&providers), false, false, false), "video/mp4"));
        // ffmpeg but Movie not listed → unavailable.
        assert!(!av(&reg(None, true, false, false), "video/mp4"));
    }

    #[test]
    fn office_requires_class_and_libreoffice() {
        let mut providers: Vec<&str> = DEFAULTS.to_vec();
        providers.push("OC\\Preview\\MSOfficeDoc");
        let msword = "application/msword";
        assert!(av(&reg(Some(&providers), false, true, false), msword));
        assert!(!av(&reg(Some(&providers), false, false, false), msword)); // no binary
        assert!(!av(&reg(None, false, true, false), msword)); // not listed

        // openxmlformats / vnd.ms / sun.xml / emf each need their class + binary.
        let mut p2: Vec<&str> = vec!["OC\\Preview\\MSOffice2007", "OC\\Preview\\EMF"];
        p2.push("OC\\Preview\\MSOffice2003");
        let r = reg(Some(&p2), false, true, false);
        assert!(av(&r, "application/vnd.openxmlformats-officedocument.wordprocessingml.document"));
        assert!(av(&r, "application/vnd.ms-excel"));
        assert!(av(&r, "image/emf"));
        assert!(!av(&r, "application/vnd.sun.xml.writer")); // StarOffice not listed
    }

    #[test]
    fn opendocument_needs_no_binary() {
        // OpenDocument (in the default list) extracts the embedded ODF thumbnail —
        // available with NO LibreOffice binary.
        let r = reg(None, false, false, false);
        assert!(av(&r, "application/vnd.oasis.opendocument.text"));
        assert!(av(&r, "application/vnd.oasis.opendocument.presentation"));
    }

    // ── enable_previews global gate + charset stripping (kept from §10.12) ──

    #[test]
    fn disabled_always_false() {
        let r = ProviderRegistry::build(false, None, true, true, true, &["HEIC", "SVG"]);
        for m in ["image/png", "image/jpeg", "video/mp4", "text/plain", "image/heic"] {
            assert!(!av(&r, m));
        }
        assert!(!r.enable_previews());
    }

    #[test]
    fn strip_charset_suffix() {
        let r = reg(None, false, false, false);
        assert!(av(&r, "text/plain; charset=utf-8"));
        assert!(av(&r, "image/png; charset=binary"));
    }

    // ── Unsupported / unknown types ────────────────────────────────────────

    #[test]
    fn unknown_type_not_available() {
        let r = reg(None, true, true, true);
        for m in [
            "application/octet-stream",
            "application/zip",
            "model/obj",
            "audio/ogg",
            "audio/flac",
            "image/avif", // no generic image/* catch-all in PHP
        ] {
            assert!(!av(&r, m), "expected unavailable: {m}");
        }
    }

    // ── imagick-family providers (startup probe parity) ────────────────────

    #[test]
    fn imagick_heic_via_provider() {
        // HEIC class enabled + imagick supports HEIC → available (no Imaginary needed).
        let r = reg_i(Some(&["OC\\Preview\\HEIC"]), false, false, false, &["HEIC"]);
        assert!(av(&r, "image/heic"));
        assert!(av(&r, "image/heif"));
        assert!(av(&r, "image/x-heic"));

        // Class enabled but imagick lacks HEIC → unavailable.
        let no_fmt = reg_i(Some(&["OC\\Preview\\HEIC"]), false, false, false, &["SVG"]);
        assert!(!av(&no_fmt, "image/heic"));

        // imagick supports HEIC but class not enabled → unavailable.
        let no_class = reg_i(None, false, false, false, &["HEIC"]);
        assert!(!av(&no_class, "image/heic"));
    }

    #[test]
    fn imagick_family_gating() {
        // Each imagick provider needs BOTH its class enabled AND the format supported.
        let r = reg_i(
            Some(&[
                "OC\\Preview\\SVG",
                "OC\\Preview\\TIFF",
                "OC\\Preview\\Illustrator",
                "OC\\Preview\\Photoshop",
                "OC\\Preview\\Postscript",
                "OC\\Preview\\PDF",
                "OC\\Preview\\Font",
                "OC\\Preview\\TGA",
                "OC\\Preview\\SGI",
            ]),
            false,
            false,
            false,
            &["SVG", "TIFF", "AI", "PSD", "EPS", "PDF", "TTF", "TGA", "SGI"],
        );
        assert!(av(&r, "image/svg+xml"));
        assert!(av(&r, "image/tiff"));
        assert!(av(&r, "application/illustrator"));
        assert!(av(&r, "application/x-photoshop"));
        assert!(av(&r, "application/postscript"));
        assert!(av(&r, "application/pdf"));
        assert!(av(&r, "application/font-sfnt"));
        assert!(av(&r, "application/x-font"));
        assert!(av(&r, "image/tga"));
        assert!(av(&r, "image/sgi"));

        // Drop a format from imagick support → that provider unavailable.
        let partial = reg_i(
            Some(&["OC\\Preview\\SVG", "OC\\Preview\\TIFF"]),
            false,
            false,
            false,
            &["SVG"], // TIFF no longer supported
        );
        assert!(av(&partial, "image/svg+xml"));
        assert!(!av(&partial, "image/tiff"));
    }

    #[test]
    fn imagick_support_alone_does_not_enable_default() {
        // Even with full imagick support, the default provider list excludes the
        // imagick family → still unavailable (the probe never widens the default set).
        let r = reg_i(
            None,
            false,
            false,
            false,
            &["SVG", "TIFF", "HEIC", "AI", "PSD", "EPS", "PDF", "TTF", "TGA", "SGI"],
        );
        for m in [
            "image/svg+xml",
            "image/tiff",
            "image/heic",
            "application/illustrator",
            "application/pdf",
        ] {
            assert!(!av(&r, m), "default list must exclude imagick family: {m}");
        }
    }

    #[test]
    fn font_provider_is_not_font_slash() {
        // PHP's Font provider matches `application/font-sfnt` / `application/x-font`
        // only — NOT `font/*`.  So `font/ttf` has no provider even with Font enabled
        // and imagick TTF support.
        let r = reg_i(Some(&["OC\\Preview\\Font"]), false, false, false, &["TTF"]);
        assert!(av(&r, "application/font-sfnt"));
        assert!(!av(&r, "font/ttf"));
        assert!(!av(&r, "font/woff2"));
    }

    #[test]
    fn imagick_availability_is_not_rust_generatable() {
        // has-preview via imagick is a hint only; native generation (11.4) stays
        // Imaginary-only.  An imagick-only HEIC preview is servable (hit) / generated
        // by PHP-FPM (miss), never by Rust.
        let r = reg_i(Some(&["OC\\Preview\\HEIC"]), false, false, false, &["HEIC"]);
        assert!(av(&r, "image/heic"));
        assert!(!r.rust_generatable("image/heic"));
    }

    #[test]
    fn parse_imagick_probe_output() {
        assert_eq!(
            parse_imagick_probe("SVG,TIFF,HEIC,"),
            vec!["SVG".to_string(), "TIFF".to_string(), "HEIC".to_string()]
        );
        assert!(parse_imagick_probe("").is_empty());
        assert!(parse_imagick_probe(",, ,").is_empty());
        // Lowercase / whitespace tolerated → normalized uppercase.
        assert_eq!(parse_imagick_probe(" svg , heic "), vec!["SVG".to_string(), "HEIC".to_string()]);
    }

    // ── rust_generatable is a strict subset of is_available ────────────────

    #[test]
    fn rust_generatable_subset() {
        let mut providers: Vec<&str> = DEFAULTS.to_vec();
        providers.push("OC\\Preview\\Imaginary");
        let r = reg(Some(&providers), false, false, true);
        for m in IMAGINARY_MIMES {
            assert!(r.rust_generatable(m), "generatable: {m}");
            assert!(av(&r, m), "generatable ⇒ available: {m}");
        }
        // text/plain is available (TXT provider) but NOT Rust-generatable.
        assert!(av(&r, "text/plain"));
        assert!(!r.rust_generatable("text/plain"));
        // No Imaginary → nothing Rust-generatable.
        let no_img = reg(None, false, false, false);
        assert!(!no_img.rust_generatable("image/png"));
    }

    // ── config-driven construction (pure parts) ────────────────────────────

    #[test]
    fn resolve_binary_config_path_wins() {
        assert!(resolve_binary(Some("/usr/bin/ffmpeg"), &["ffmpeg"]));
        // Empty path falls through (to PATH search — not asserted here, env-dependent).
    }
}
