//! YAML scenario loader + operation executor (Phase 16.4).
//!
//! A scenario is an ordered list of typed ops replayed **identically** against
//! both the SUT and the Oracle. The executor returns each op's status so the
//! runner can flag HTTP-level mismatches; the primary oracle is the DB delta.
//!
//! A scenario may also declare `cleanup` ops: replayed **after** the after-
//! snapshot (so they never enter the diff), on both sides, to restore the
//! pre-scenario state and make the scenario re-runnable (Phase 16.7).
//!
//! Covers the core WebDAV ops, OCS share ops, and the Phase 16.10 upload
//! ops (`chunked_upload_v2`, `bulk`, `ocs_user_quota`), each grounded
//! against the real protocol rather than guessed (deviation 16.2).

use std::collections::HashMap;
use std::fs;

use anyhow::{bail, Context, Result};
use reqwest::header::{HeaderMap, HeaderValue};
use reqwest::Method;
use serde::Deserialize;

use crate::client::NextcloudClient;

#[derive(Debug, Deserialize)]
pub struct Scenario {
    pub name: String,
    pub ops: Vec<Op>,
    /// Ops replayed after the after-snapshot on both sides (not diffed), to
    /// restore pre-scenario state so the scenario can be re-run.
    #[serde(default)]
    pub cleanup: Vec<Op>,
    /// `table.column` entries promoted to `stable` for this scenario only —
    /// for client-dictated values (e.g. `X-OC-Mtime`) whose absolute value is
    /// deterministic and must be compared verbatim despite the registry's
    /// masking (Phase 16.9).
    #[serde(default)]
    pub stable_overrides: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum Op {
    Put {
        path: String,
        #[serde(default)]
        body_file: Option<String>,
        #[serde(default)]
        body: Option<String>,
        #[serde(default)]
        headers: std::collections::BTreeMap<String, String>,
        /// Also capture + compare the response body across sides (rejection
        /// parity: same status is not enough, the error shape must match too).
        #[serde(default)]
        compare_body: bool,
        /// Capture response headers into variables (`var: Header-Name`).
        #[serde(default)]
        capture_headers: std::collections::BTreeMap<String, String>,
    },
    Get {
        path: String,
        /// Also capture + compare the response body across sides (rejection
        /// parity for e.g. preview 404s; leave off for generated bytes).
        #[serde(default)]
        compare_body: bool,
    },
    Delete {
        path: String,
        /// Optional headers (e.g. `X-NC-Skip-Trashbin: "true"` for a hard
        /// delete that leaves no trash residue — PHP supports it too,
        /// Storage.php:128).
        #[serde(default)]
        headers: std::collections::BTreeMap<String, String>,
    },
    Mkcol {
        path: String,
    },
    Move {
        from: String,
        to: String,
    },
    Copy {
        from: String,
        to: String,
    },
    Propfind {
        path: String,
        #[serde(default)]
        depth: Option<u32>,
    },
    Proppatch {
        path: String,
        body: String,
    },
    /// Chunked upload v2 (Phase 16.10): MKCOL the upload dir (e.g.
    /// `/remote.php/dav/uploads/admin/{upload_id}`) → PUT each chunk → MOVE
    /// `.file` to `destination`. Both sides get the SAME upload dir so any DB
    /// rows keyed on it are comparable.
    ChunkedUploadV2 {
        upload_dir: String,
        destination: String,
        chunks: Vec<ChunkBody>,
    },
    /// Bulk upload (Phase 16.10): one `multipart/related` POST to `/dav/bulk`
    /// with per-part `X-File-Path` headers (grounded in PHP
    /// `apps/dav/lib/BulkUpload/BulkUploadPlugin.php`).
    Bulk {
        files: Vec<BulkFile>,
    },
    /// OCS user-setting update (Phase 16.10): quota scenarios set/restore the
    /// user's quota around an over-quota PUT.
    OcsUserQuota {
        user: String,
        quota: String,
    },
    /// OCS share create (Phase 16.7). `capture` maps a variable name to a
    /// dotted JSON path in the OCS response (e.g. `ocs.data.id`) for later
    /// interpolation into cleanup ops (`{var}`).
    ShareCreate {
        path: String,
        share_type: u32,
        #[serde(default)]
        share_with: Option<String>,
        #[serde(default)]
        permissions: Option<u32>,
        #[serde(default)]
        capture: std::collections::BTreeMap<String, String>,
    },
    /// OCS share delete; `id` may contain `{var}` interpolations.
    ShareDelete {
        id: String,
    },
}

/// One chunk of a chunked upload / one file of a bulk upload.
#[derive(Debug, Deserialize)]
pub struct ChunkBody {
    #[serde(default)]
    pub body_file: Option<String>,
    #[serde(default)]
    pub body: Option<String>,
}

/// One file inside a bulk upload: destination path (relative to the user
/// root) + content (+ optional client-dictated mtime).
#[derive(Debug, Deserialize)]
pub struct BulkFile {
    pub path: String,
    #[serde(default)]
    pub body_file: Option<String>,
    #[serde(default)]
    pub body: Option<String>,
    #[serde(default)]
    pub mtime: Option<u64>,
}

impl Scenario {
    pub fn load(path: &str) -> Result<Self> {
        let text = fs::read_to_string(path).with_context(|| format!("reading {path}"))?;
        serde_yaml::from_str(&text).with_context(|| format!("parsing scenario {path}"))
    }
}

pub struct OpResult {
    pub op: String,
    pub status: u16,
    /// Response body, captured only for ops with `compare_body` (rejection
    /// parity checks) — `None` otherwise.
    pub body: Option<String>,
}

/// Resolve a fixture body. `body_file` is relative to the crate's `fixtures/`.
fn body_bytes(body_file: &Option<String>, body: &Option<String>) -> Result<Vec<u8>> {
    if let Some(f) = body_file {
        let p = format!("{}/fixtures/{f}", env!("CARGO_MANIFEST_DIR"));
        return fs::read(&p).with_context(|| format!("reading fixture {p}"));
    }
    if let Some(b) = body {
        return Ok(b.as_bytes().to_vec());
    }
    Ok(Vec::new())
}

fn put_headers(h: &std::collections::BTreeMap<String, String>) -> Result<HeaderMap> {
    let mut map = HeaderMap::new();
    for (k, v) in h {
        let name = reqwest::header::HeaderName::from_bytes(k.as_bytes())
            .with_context(|| format!("header name {k:?}"))?;
        let val = HeaderValue::from_str(v).with_context(|| format!("header value {v:?}"))?;
        map.insert(name, val);
    }
    Ok(map)
}

fn describe(op: &Op) -> String {
    match op {
        Op::Put { path, .. } => format!("PUT {path}"),
        Op::Get { path, .. } => format!("GET {path}"),
        Op::Delete { path, .. } => format!("DELETE {path}"),
        Op::Mkcol { path } => format!("MKCOL {path}"),
        Op::Move { from, to } => format!("MOVE {from} -> {to}"),
        Op::Copy { from, to } => format!("COPY {from} -> {to}"),
        Op::Propfind { path, depth } => format!("PROPFIND {path} (depth {})", depth.unwrap_or(0)),
        Op::Proppatch { path, .. } => format!("PROPPATCH {path}"),
        Op::ShareCreate { path, share_type, .. } => {
            format!("SHARE_CREATE {path} (type {share_type})")
        }
        Op::ShareDelete { id } => format!("SHARE_DELETE {id}"),
        Op::ChunkedUploadV2 { upload_dir, destination, chunks } => {
            format!("CHUNKED_V2 {upload_dir} -> {destination} ({} chunks)", chunks.len())
        }
        Op::Bulk { files } => {
            format!("BULK ({} files)", files.len())
        }
        Op::OcsUserQuota { user, quota } => format!("OCS_QUOTA {user}={quota}"),
    }
}

/// Substitute `{var}` occurrences from the captured-values map.
fn interpolate(s: &str, vars: &HashMap<String, String>) -> String {
    let mut out = s.to_string();
    for (k, v) in vars {
        out = out.replace(&format!("{{{k}}}"), v);
    }
    out
}

/// Extract a dotted JSON path (e.g. `ocs.data.id`) from an OCS response body.
fn capture_from_json(body: &str, dotted: &str) -> Result<String> {
    let mut val: serde_json::Value =
        serde_json::from_str(body).with_context(|| format!("parsing OCS JSON: {body:.200}"))?;
    for seg in dotted.split('.') {
        val = val
            .get(seg)
            .cloned()
            .with_context(|| format!("JSON path {dotted:?} not found in {body:.200}"))?;
    }
    match val {
        serde_json::Value::String(s) => Ok(s),
        serde_json::Value::Number(n) => Ok(n.to_string()),
        other => Ok(other.to_string()),
    }
}

/// Replay ops against one instance, returning per-op statuses. Captured values
/// (per-side — ids/fileids differ between SUT and Oracle) land in `vars` for
/// interpolation into later ops (share cleanup, preview requests).
pub async fn run_ops(
    client: &NextcloudClient,
    ops: &[Op],
    vars: &mut HashMap<String, String>,
) -> Result<Vec<OpResult>> {
    let mut results = Vec::new();
    for op in ops {
        let resp = match op {
            Op::Put {
                path,
                body_file,
                body,
                headers,
                compare_body,
                capture_headers,
            } => {
                let bytes = body_bytes(body_file, body)?;
                let resp = client.put(&interpolate(path, vars), bytes, put_headers(headers)?).await?;
                let status = resp.status();
                for (var, header) in capture_headers {
                    let val = resp
                        .headers()
                        .get(header.as_str())
                        .and_then(|v| v.to_str().ok())
                        .with_context(|| format!("capturing header {header:?}"))?
                        .to_string();
                    vars.insert(var.clone(), val);
                }
                let body_text = if *compare_body {
                    Some(resp.text().await.with_context(|| "reading body for compare_body")?)
                } else {
                    None
                };
                results.push(OpResult {
                    op: describe(op),
                    status: status.as_u16(),
                    body: body_text,
                });
                continue;
            }
            Op::Get { path, compare_body } => {
                let resp = client.get(path).await?;
                let status = resp.status();
                let body_text = if *compare_body {
                    Some(resp.text().await.with_context(|| "reading body for compare_body")?)
                } else {
                    None
                };
                results.push(OpResult {
                    op: describe(op),
                    status: status.as_u16(),
                    body: body_text,
                });
                continue;
            }
            Op::Delete { path, headers } => {
                client.delete(&interpolate(path, vars), put_headers(headers)?).await?
            }
            Op::Mkcol { path } => client.mkcol(path).await?,
            Op::Move { from, to } => {
                client.move_(&interpolate(from, vars), &interpolate(to, vars)).await?
            }
            Op::Copy { from, to } => {
                client.copy(&interpolate(from, vars), &interpolate(to, vars)).await?
            }
            Op::Propfind { path, depth } => {
                client.propfind(&interpolate(path, vars), depth.unwrap_or(0), None).await?
            }
            Op::Proppatch { path, body } => client.proppatch(&interpolate(path, vars), body).await?,
            Op::ShareCreate {
                path,
                share_type,
                share_with,
                permissions,
                capture,
            } => {
                let mut params = vec![
                    ("path".to_string(), interpolate(path, vars)),
                    ("shareType".to_string(), share_type.to_string()),
                ];
                if let Some(w) = share_with {
                    params.push(("shareWith".to_string(), w.clone()));
                }
                if let Some(p) = permissions {
                    params.push(("permissions".to_string(), p.to_string()));
                }
                let resp = client.share_create(&params).await?;
                if !capture.is_empty() {
                    let status = resp.status();
                    let body = resp.text().await.with_context(|| "reading share_create body")?;
                    anyhow::ensure!(
                        status.is_success(),
                        "share_create failed ({status}): {body:.300}"
                    );
                    for (var, dotted) in capture {
                        let v = capture_from_json(&body, dotted)?;
                        vars.insert(var.clone(), v);
                    }
                    // Captured the values; record status and continue without
                    // re-reading the consumed body.
                    results.push(OpResult {
                        op: describe(op),
                        status: status.as_u16(),
                        body: None,
                    });
                    continue;
                }
                resp
            }
            Op::ShareDelete { id } => client.share_delete(&interpolate(id, vars)).await?,
            Op::ChunkedUploadV2 {
                upload_dir,
                destination,
                chunks,
            } => {
                // MKCOL → PUT chunks → MOVE `.file`. Each step's status is
                // recorded and compared across sides — a rejection at any step
                // is a divergence to report, never a hard abort (the oracle
                // must show *where* the sides part, not die on the first one).
                let dir = interpolate(upload_dir, vars);
                let mkcol = client.mkcol(&dir).await?;
                results.push(OpResult {
                    op: format!("CHUNKED_V2 MKCOL {dir}"),
                    status: mkcol.status().as_u16(),
                    body: None,
                });
                for (i, chunk) in chunks.iter().enumerate() {
                    let bytes = body_bytes(&chunk.body_file, &chunk.body)?;
                    let resp = client
                        .put(&format!("{dir}/{}", i + 1), bytes, HeaderMap::new())
                        .await?;
                    results.push(OpResult {
                        op: format!("CHUNKED_V2 PUT {dir}/{}", i + 1),
                        status: resp.status().as_u16(),
                        body: None,
                    });
                }
                // Assemble: MOVE {dir}/.file -> destination.
                client.move_(&format!("{dir}/.file"), &interpolate(destination, vars)).await?
            }
            Op::Bulk { files } => {
                let boundary = "difftest-bulk-boundary";
                let mut body = Vec::new();
                for f in files {
                    let bytes = body_bytes(&f.body_file, &f.body)?;
                    body.extend_from_slice(format!("--{boundary}\r\n").as_bytes());
                    body.extend_from_slice(
                        format!("X-File-Path: {}\r\n", interpolate(&f.path, vars)).as_bytes(),
                    );
                    if let Some(m) = f.mtime {
                        body.extend_from_slice(format!("X-File-Mtime: {m}\r\n").as_bytes());
                    }
                    body.extend_from_slice(format!("Content-Length: {}\r\n", bytes.len()).as_bytes());
                    body.extend_from_slice(b"\r\n");
                    body.extend_from_slice(&bytes);
                    body.extend_from_slice(b"\r\n");
                }
                body.extend_from_slice(format!("--{boundary}--\r\n").as_bytes());
                let mut h = HeaderMap::new();
                h.insert(
                    reqwest::header::CONTENT_TYPE,
                    HeaderValue::from_str(&format!("multipart/related; boundary={boundary}"))?,
                );
                client.request(Method::POST, "/remote.php/dav/bulk", h, Some(body)).await?
            }
            Op::OcsUserQuota { user, quota } => {
                client.ocs_user_update(&interpolate(user, vars), "quota", &interpolate(quota, vars)).await?
            }
        };
        results.push(OpResult {
            op: describe(op),
            status: resp.status().as_u16(),
            body: None,
        });
    }
    Ok(results)
}

/// Replay the scenario's main ops against one instance.
pub async fn run(
    client: &NextcloudClient,
    sc: &Scenario,
    vars: &mut HashMap<String, String>,
) -> Result<Vec<OpResult>> {
    run_ops(client, &sc.ops, vars).await
}

/// Replay the scenario's cleanup ops (after the after-snapshot; not diffed).
/// All cleanup ops are attempted even if earlier ones fail; errors accumulate.
pub async fn run_cleanup(
    client: &NextcloudClient,
    sc: &Scenario,
    vars: &HashMap<String, String>,
) -> Result<()> {
    let mut errors = Vec::new();
    let mut vars_mut = vars.clone();
    for op in &sc.cleanup {
        if let Err(e) = run_ops(client, std::slice::from_ref(op), &mut vars_mut).await {
            errors.push(format!("{}: {e:#}", describe(op)));
        }
    }
    if errors.is_empty() {
        Ok(())
    } else {
        bail!("cleanup failed: {}", errors.join("; "))
    }
}
