//! YAML scenario loader + operation executor (Phase 16.4).
//!
//! A scenario is an ordered list of typed ops replayed **identically** against
//! both the SUT and the Oracle. The executor returns each op's status so the
//! runner can flag HTTP-level mismatches; the primary oracle is the DB delta.
//!
//! A scenario may also declare `cleanup` ops: replayed **after** the after-
//! snapshot (so they never enter the diff), on both sides, to restore the
//! pre-scenario state and make the scenario re-runnable (Phase 16.7).
//!
//! Covers the core WebDAV ops, OCS share ops, and the Phase 16.10 upload
//! ops (`chunked_upload_v2`, `bulk`, `ocs_user_quota`), each grounded
//! against the real protocol rather than guessed (deviation 16.2).

use std::collections::HashMap;
use std::fs;

use anyhow::{bail, Context, Result};
use reqwest::header::{HeaderMap, HeaderValue};
use reqwest::Method;
use serde::Deserialize;

use crate::client::NextcloudClient;

#[derive(Debug, Deserialize)]
pub struct Scenario {
    pub name: String,
    pub ops: Vec<Op>,
    /// Ops replayed after the after-snapshot on both sides (not diffed), to
    /// restore pre-scenario state so the scenario can be re-run.
    #[serde(default)]
    pub cleanup: Vec<Op>,
    /// `table.column` entries promoted to `stable` for this scenario only —
    /// for client-dictated values (e.g. `X-OC-Mtime`) whose absolute value is
    /// deterministic and must be compared verbatim despite the registry's
    /// masking (Phase 16.9).
    #[serde(default)]
    pub stable_overrides: Vec<String>,
    /// Auth mode for all ops: `bearer` = `Authorization: Bearer` with a
    /// per-side app token (2026-08-14); absent = Basic auth with the admin
    /// password (the default for every other scenario).
    #[serde(default)]
    pub auth: Option<String>,
}

fn default_true() -> bool {
    true
}

#[derive(Debug, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum Op {
    Put {
        path: String,
        #[serde(default)]
        body_file: Option<String>,
        #[serde(default)]
        body: Option<String>,
        #[serde(default)]
        headers: std::collections::BTreeMap<String, String>,
        /// Also capture + compare the response body across sides (rejection
        /// parity: same status is not enough, the error shape must match too).
        #[serde(default)]
        compare_body: bool,
        /// Skip the cross-side STATUS equality assertion for this op (the
        /// statuses are still printed).  For recorded intentional divergences
        /// — e.g. the SUT's REQ §13.1 OC-Checksum rejection (400) vs PHP
        /// accepting the header unverified (204); the row consequences are
        /// listed in divergences.yaml.
        #[serde(default = "default_true")]
        compare_status: bool,
        /// Capture response headers into variables (`var: Header-Name`).
        #[serde(default)]
        capture_headers: std::collections::BTreeMap<String, String>,
    },
    Get {
        path: String,
        /// Also capture + compare the response body across sides (rejection
        /// parity for e.g. preview 404s; leave off for generated bytes).
        #[serde(default)]
        compare_body: bool,
        /// Capture + compare the response **bytes** verbatim (Phase 16.11
        /// Imaginary): with one shared Imaginary backend the generated preview
        /// bytes must be byte-identical across sides. Mutually exclusive with
        /// `compare_body` (bytes take precedence — binary bodies).
        #[serde(default)]
        compare_bytes: bool,
    },
    Delete {
        path: String,
        /// Optional headers (e.g. `X-NC-Skip-Trashbin: "true"` for a hard
        /// delete that leaves no trash residue — PHP supports it too,
        /// Storage.php:128).
        #[serde(default)]
        headers: std::collections::BTreeMap<String, String>,
    },
    Mkcol {
        path: String,
    },
    Move {
        from: String,
        to: String,
    },
    Copy {
        from: String,
        to: String,
    },
    Propfind {
        path: String,
        #[serde(default)]
        depth: Option<u32>,
        /// Explicit `<d:prop>` body (22.5 — the desktop client's narrow prop
        /// set).  Absent = bare PROPFIND = allprop.
        #[serde(default)]
        body: Option<String>,
    },
    Proppatch {
        path: String,
        body: String,
    },
    /// Chunked upload v2 (Phase 16.10): MKCOL the upload dir (e.g.
    /// `/remote.php/dav/uploads/admin/{upload_id}`) → PUT each chunk → MOVE
    /// `.file` to `destination`. Both sides get the SAME upload dir so any DB
    /// rows keyed on it are comparable.
    ChunkedUploadV2 {
        upload_dir: String,
        destination: String,
        chunks: Vec<ChunkBody>,
    },
    /// Bulk upload (Phase 16.10): one `multipart/related` POST to `/dav/bulk`
    /// with per-part `X-File-Path` headers (grounded in PHP
    /// `apps/dav/lib/BulkUpload/BulkUploadPlugin.php`).
    Bulk {
        files: Vec<BulkFile>,
    },
    /// OCS user-setting update (Phase 16.10): quota scenarios set/restore the
    /// user's quota around an over-quota PUT.
    OcsUserQuota {
        user: String,
        quota: String,
    },
    /// OCS share create (Phase 16.7). `capture` maps a variable name to a
    /// dotted JSON path in the OCS response (e.g. `ocs.data.id`) for later
    /// interpolation into cleanup ops (`{var}`).
    ShareCreate {
        path: String,
        share_type: u32,
        #[serde(default)]
        share_with: Option<String>,
        #[serde(default)]
        permissions: Option<u32>,
        #[serde(default)]
        capture: std::collections::BTreeMap<String, String>,
    },
    /// OCS share delete; `id` may contain `{var}` interpolations.
    ShareDelete {
        id: String,
    },
}

/// One chunk of a chunked upload / one file of a bulk upload.
#[derive(Debug, Deserialize)]
pub struct ChunkBody {
    #[serde(default)]
    pub body_file: Option<String>,
    #[serde(default)]
    pub body: Option<String>,
}

/// One file inside a bulk upload: destination path (relative to the user
/// root) + content (+ optional client-dictated mtime).
#[derive(Debug, Deserialize)]
pub struct BulkFile {
    pub path: String,
    #[serde(default)]
    pub body_file: Option<String>,
    #[serde(default)]
    pub body: Option<String>,
    #[serde(default)]
    pub mtime: Option<u64>,
}

impl Scenario {
    pub fn load(path: &str) -> Result<Self> {
        let text = fs::read_to_string(path).with_context(|| format!("reading {path}"))?;
        serde_yaml::from_str(&text).with_context(|| format!("parsing scenario {path}"))
    }
}

pub struct OpResult {
    pub op: String,
    pub status: u16,
    /// Response body, captured only for ops with `compare_body` (rejection
    /// parity checks) — `None` otherwise.
    pub body: Option<String>,
    /// Response **bytes**, captured only for ops with `compare_bytes`
    /// (byte-exact parity for generated previews) — `None` otherwise.
    pub body_bytes: Option<Vec<u8>>,
    /// Structural shape of a PROPFIND multistatus (22.6): response
    /// cardinality + the `href` set.  The delta diff is blind to a
    /// truncated/empty listing — a panicked or short-circuited request
    /// writes no deltas — so the shape is the response-correctness surface.
    pub propfind_shape: Option<PropfindShape>,
    /// Wall time of the op's HTTP round-trip (Phase 17 — benchmark harness).
    pub elapsed: std::time::Duration,
}

/// Structural shape of a PROPFIND multistatus response (22.6).  Compared
/// across sides instead of bytes — the XML prolog, namespace prefixes, and
/// etag quoting differ in known ways between PHP (sabre) and dav-server-rs.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct PropfindShape {
    /// Number of `<d:response>` elements.
    pub responses: usize,
    /// The `href` values, in document order.
    pub hrefs: Vec<String>,
    /// Per-node prop availability (2026-08-14): `href` → the prop names in
    /// the 200 and 404 propstats.  The web files app's propfind A/B exposed
    /// availability gaps (reminder-due-date PHP 200 vs Rust 404,
    /// quota-on-files PHP 404 vs Rust 200) that cardinality+hrefs cannot
    /// catch.
    pub props: std::collections::BTreeMap<String, (Vec<String>, Vec<String>)>,
}

/// Extract the multistatus shape from a PROPFIND response body.
/// Prefix-agnostic (the sides may use different namespace prefixes): matches
/// `<*:response` / `<*:href>` element names and takes the href text.
fn propfind_shape(body: &str) -> PropfindShape {
    let mut shape = PropfindShape::default();
    let bytes = body.as_bytes();
    let mut i = 0usize;
    // Per-node accumulation state: the current response's href, the current
    // propstat's pending prop names (the <d:status> comes AFTER the <d:prop>
    // block), and the depth inside <d:prop> so nested value elements
    // (sharee details, share-type, ...) are not counted as props.
    let mut cur_href: Option<String> = None;
    let mut pending: Vec<String> = Vec::new();
    let mut prop_depth: u8 = 0;
    while i < bytes.len() {
        // Next '<'; then the tag name up to whitespace/'/'/'>'.
        let Some(rel) = body[i..].find('<') else { break };
        let name_start = i + rel + 1;
let closing = body[name_start..].starts_with('/');
        let scan_start = name_start + usize::from(closing);
        let Some(name_len) = body[scan_start..]
            .find(|c| c == '>' || c == ' ' || c == '/' || c == '\n' || c == '\t' || c == '\r')
        else {
            break;
        };
        let name = &body[scan_start..scan_start + name_len];
        let after = scan_start + name_len;
        // Self-closing `<d:collection/>`: the char after the name is '/'.
        let self_closing = !closing && body[after..].starts_with('/');
        let elem = name;
        let elem = elem.rsplit(':').next().unwrap_or(elem);
        match elem {
            "response" if !closing => {
                shape.responses += 1;
                cur_href = None;
                pending.clear();
                prop_depth = 0;
            }
            "href" if !closing => {
                // Content between '>' and the closing tag.
                if let Some(gt) = body[after..].find('>') {
                    let content = after + gt + 1;
                    if let Some(close) = body[content..].find("</") {
                        let href = body[content..content + close].to_string();
                        shape.hrefs.push(href.clone());
                        cur_href = Some(href);
                    }
                }
            }
            "prop" if !closing => {
                pending.clear();
                prop_depth = 1;
            }
            "prop" => {}
            "status" if !closing => {
                // The propstat's status comes AFTER its <d:prop> block —
                // classify the buffered prop names.  Only the immediate
                // value counts (a later propstat's 404 must not leak in).
                let is_200 = if let Some(gt) = body[after..].find('>') {
                    let content = after + gt + 1;
                    let close = body[content..].find("</").unwrap_or(body.len() - content);
                    !body[content..content + close].contains("404")
                } else {
                    true
                };
                if let Some(href) = &cur_href {
                    let entry = shape.props.entry(href.clone()).or_default();
                    if is_200 {
                        entry.0.append(&mut pending);
                    } else {
                        entry.1.append(&mut pending);
                    }
                } else {
                    pending.clear();
                }
            }
            "propstat" | "multistatus" => {}
            _ => {
                if closing {
                    // A closing tag ends its element: a direct prop's close
                    // returns to depth 1; a nested element's close descends.
                    if prop_depth >= 2 {
                        prop_depth -= 1;
                    }
                } else if prop_depth == 1 {
                    // A direct child of <d:prop>: a prop name.  Non-self-
                    // closing props contain nested value elements (depth 2).
                    pending.push(elem.to_string());
                    if !self_closing {
                        prop_depth = 2;
                    }
                } else if prop_depth >= 2 && !self_closing {
                    // Nested value elements (sharee details, share-type...)
                    // — tracked only for the closing-tag depth bookkeeping.
                    prop_depth += 1;
                }
            }
        }
        i = after;
    }
    shape
}

/// Resolve a fixture body. `body_file` is relative to the crate's `fixtures/`.
impl Op {
    /// Whether the runner must assert equal statuses across sides (default
    /// true; `compare_status: false` marks a recorded intentional divergence).
    pub fn compare_status(&self) -> bool {
        match self {
            Op::Put { compare_status, .. } => *compare_status,
            _ => true,
        }
    }
}

fn body_bytes(body_file: &Option<String>, body: &Option<String>) -> Result<Vec<u8>> {
    if let Some(f) = body_file {
        let p = format!("{}/fixtures/{f}", env!("CARGO_MANIFEST_DIR"));
        return fs::read(&p).with_context(|| format!("reading fixture {p}"));
    }
    if let Some(b) = body {
        return Ok(b.as_bytes().to_vec());
    }
    Ok(Vec::new())
}

fn put_headers(h: &std::collections::BTreeMap<String, String>) -> Result<HeaderMap> {
    let mut map = HeaderMap::new();
    for (k, v) in h {
        let name = reqwest::header::HeaderName::from_bytes(k.as_bytes())
            .with_context(|| format!("header name {k:?}"))?;
        let val = HeaderValue::from_str(v).with_context(|| format!("header value {v:?}"))?;
        map.insert(name, val);
    }
    Ok(map)
}

fn describe(op: &Op) -> String {
    match op {
        Op::Put { path, .. } => format!("PUT {path}"),
        Op::Get { path, .. } => format!("GET {path}"),
        Op::Delete { path, .. } => format!("DELETE {path}"),
        Op::Mkcol { path } => format!("MKCOL {path}"),
        Op::Move { from, to } => format!("MOVE {from} -> {to}"),
        Op::Copy { from, to } => format!("COPY {from} -> {to}"),
        Op::Propfind { path, depth, body } => format!(
            "PROPFIND {path} (depth {}{})",
            depth.unwrap_or(0),
            if body.is_some() { ", narrow prop set" } else { "" }
        ),
        Op::Proppatch { path, .. } => format!("PROPPATCH {path}"),
        Op::ShareCreate {
            path, share_type, ..
        } => {
            format!("SHARE_CREATE {path} (type {share_type})")
        }
        Op::ShareDelete { id } => format!("SHARE_DELETE {id}"),
        Op::ChunkedUploadV2 {
            upload_dir,
            destination,
            chunks,
        } => {
            format!(
                "CHUNKED_V2 {upload_dir} -> {destination} ({} chunks)",
                chunks.len()
            )
        }
        Op::Bulk { files } => {
            format!("BULK ({} files)", files.len())
        }
        Op::OcsUserQuota { user, quota } => format!("OCS_QUOTA {user}={quota}"),
    }
}

/// Substitute `{var}` occurrences from the captured-values map.
fn interpolate(s: &str, vars: &HashMap<String, String>) -> String {
    let mut out = s.to_string();
    for (k, v) in vars {
        out = out.replace(&format!("{{{k}}}"), v);
    }
    out
}

/// Extract a dotted JSON path (e.g. `ocs.data.id`) from an OCS response body.
fn capture_from_json(body: &str, dotted: &str) -> Result<String> {
    let mut val: serde_json::Value =
        serde_json::from_str(body).with_context(|| format!("parsing OCS JSON: {body:.200}"))?;
    for seg in dotted.split('.') {
        val = val
            .get(seg)
            .cloned()
            .with_context(|| format!("JSON path {dotted:?} not found in {body:.200}"))?;
    }
    match val {
        serde_json::Value::String(s) => Ok(s),
        serde_json::Value::Number(n) => Ok(n.to_string()),
        other => Ok(other.to_string()),
    }
}

/// Replay ops against one instance, returning per-op statuses. Captured values
/// (per-side — ids/fileids differ between SUT and Oracle) land in `vars` for
/// interpolation into later ops (share cleanup, preview requests).
pub async fn run_ops(
    client: &NextcloudClient,
    ops: &[Op],
    vars: &mut HashMap<String, String>,
) -> Result<Vec<OpResult>> {
    let mut results = Vec::new();
    for op in ops {
        let start = std::time::Instant::now();
        let resp = match op {
            Op::Put {
                path,
                body_file,
                body,
                headers,
                compare_body,
                compare_status: _,
                capture_headers,
            } => {
                let bytes = body_bytes(body_file, body)?;
                let resp = client
                    .put(&interpolate(path, vars), bytes, put_headers(headers)?)
                    .await?;
                let status = resp.status();
                for (var, header) in capture_headers {
                    let val = resp
                        .headers()
                        .get(header.as_str())
                        .and_then(|v| v.to_str().ok())
                        .with_context(|| format!("capturing header {header:?}"))?
                        .to_string();
                    vars.insert(var.clone(), val);
                }
                let body_text = if *compare_body {
                    Some(
                        resp.text()
                            .await
                            .with_context(|| "reading body for compare_body")?,
                    )
                } else {
                    None
                };
                results.push(OpResult {
                    op: describe(op),
                    status: status.as_u16(),
                    body: body_text,
                    body_bytes: None,
                    propfind_shape: None,
                    elapsed: start.elapsed(),
                });
                continue;
            }
            Op::Get {
                path,
                compare_body,
                compare_bytes,
            } => {
                let resp = client.get(path).await?;
                let status = resp.status();
                // compare_bytes wins: it consumes the response body as raw
                // bytes (binary preview data); compare_body reads text.
                let (body_text, body_bytes) = if *compare_bytes {
                    let bytes = resp
                        .bytes()
                        .await
                        .with_context(|| "reading body for compare_bytes")?;
                    (None, Some(bytes.to_vec()))
                } else if *compare_body {
                    (
                        Some(
                            resp.text()
                                .await
                                .with_context(|| "reading body for compare_body")?,
                        ),
                        None,
                    )
                } else {
                    (None, None)
                };
                results.push(OpResult {
                    op: describe(op),
                    status: status.as_u16(),
                    body: body_text,
                    body_bytes,
                    propfind_shape: None,
                    elapsed: start.elapsed(),
                });
                continue;
            }
            Op::Delete { path, headers } => {
                client
                    .delete(&interpolate(path, vars), put_headers(headers)?)
                    .await?
            }
            Op::Mkcol { path } => client.mkcol(path).await?,
            Op::Move { from, to } => {
                client
                    .move_(&interpolate(from, vars), &interpolate(to, vars))
                    .await?
            }
            Op::Copy { from, to } => {
                client
                    .copy(&interpolate(from, vars), &interpolate(to, vars))
                    .await?
            }
            Op::Propfind { path, depth, body } => {
                let resp = client
                    .propfind(
                        &interpolate(path, vars),
                        depth.unwrap_or(0),
                        body.as_deref(),
                    )
                    .await?;
                let status = resp.status();
                // Consume the response body: dav-server-rs streams PROPFIND
                // responses, and read_dir + the batch queries run inside the
                // stream — dropping the body skips the very work the replay
                // must reproduce (the oracle's PHP builds the response
                // eagerly).  Phase-21 milestone: the SUT's depth-1 read side
                // effects (lazy cache row, batches) never ran in the replay.
                // The body is deliberately NOT recorded for comparison — the
                // propfind XML shapes differ in known ways (prolog, namespace
                // prefixes, etag quote-escaping); the delta diff is the
                // propfind's parity surface.  The multistatus SHAPE (22.6:
                // response cardinality + href set) is extracted instead — the
                // tripwire for an empty/truncated listing, which writes no
                // deltas and passes the delta diff.
                let text = resp.text().await.with_context(|| "reading propfind body")?;
                results.push(OpResult {
                    op: describe(op),
                    status: status.as_u16(),
                    body: None,
                    body_bytes: None,
                    propfind_shape: Some(propfind_shape(&text)),
                    elapsed: start.elapsed(),
                });
                continue;
            }
            Op::Proppatch { path, body } => {
                client.proppatch(&interpolate(path, vars), body).await?
            }
            Op::ShareCreate {
                path,
                share_type,
                share_with,
                permissions,
                capture,
            } => {
                let mut params = vec![
                    ("path".to_string(), interpolate(path, vars)),
                    ("shareType".to_string(), share_type.to_string()),
                ];
                if let Some(w) = share_with {
                    params.push(("shareWith".to_string(), w.clone()));
                }
                if let Some(p) = permissions {
                    params.push(("permissions".to_string(), p.to_string()));
                }
                let resp = client.share_create(&params).await?;
                if !capture.is_empty() {
                    let status = resp.status();
                    let body = resp
                        .text()
                        .await
                        .with_context(|| "reading share_create body")?;
                    anyhow::ensure!(
                        status.is_success(),
                        "share_create failed ({status}): {body:.300}"
                    );
                    for (var, dotted) in capture {
                        let v = capture_from_json(&body, dotted)?;
                        vars.insert(var.clone(), v);
                    }
                    // Captured the values; record status and continue without
                    // re-reading the consumed body.
                    results.push(OpResult {
                        op: describe(op),
                        status: status.as_u16(),
                        body: None,
                        body_bytes: None,
                        propfind_shape: None,
                        elapsed: start.elapsed(),
                    });
                    continue;
                }
                resp
            }
            Op::ShareDelete { id } => client.share_delete(&interpolate(id, vars)).await?,
            Op::ChunkedUploadV2 {
                upload_dir,
                destination,
                chunks,
            } => {
                // MKCOL → PUT chunks → MOVE `.file`. Each step's status is
                // recorded and compared across sides — a rejection at any step
                // is a divergence to report, never a hard abort (the oracle
                // must show *where* the sides part, not die on the first one).
                let dir = interpolate(upload_dir, vars);
                let mkcol = client.mkcol(&dir).await?;
                results.push(OpResult {
                    op: format!("CHUNKED_V2 MKCOL {dir}"),
                    status: mkcol.status().as_u16(),
                    body: None,
                    body_bytes: None,
                    propfind_shape: None,
                    elapsed: start.elapsed(),
                });
                for (i, chunk) in chunks.iter().enumerate() {
                    let bytes = body_bytes(&chunk.body_file, &chunk.body)?;
                    let resp = client
                        .put(&format!("{dir}/{}", i + 1), bytes, HeaderMap::new())
                        .await?;
                    results.push(OpResult {
                        op: format!("CHUNKED_V2 PUT {dir}/{}", i + 1),
                        status: resp.status().as_u16(),
                        body: None,
                        body_bytes: None,
                        propfind_shape: None,
                        elapsed: start.elapsed(),
                    });
                }
                // Assemble: MOVE {dir}/.file -> destination.
                client
                    .move_(&format!("{dir}/.file"), &interpolate(destination, vars))
                    .await?
            }
            Op::Bulk { files } => {
                let boundary = "difftest-bulk-boundary";
                let mut body = Vec::new();
                for f in files {
                    let bytes = body_bytes(&f.body_file, &f.body)?;
                    body.extend_from_slice(format!("--{boundary}\r\n").as_bytes());
                    body.extend_from_slice(
                        format!("X-File-Path: {}\r\n", interpolate(&f.path, vars)).as_bytes(),
                    );
                    if let Some(m) = f.mtime {
                        body.extend_from_slice(format!("X-File-Mtime: {m}\r\n").as_bytes());
                    }
                    body.extend_from_slice(
                        format!("Content-Length: {}\r\n", bytes.len()).as_bytes(),
                    );
                    body.extend_from_slice(b"\r\n");
                    body.extend_from_slice(&bytes);
                    body.extend_from_slice(b"\r\n");
                }
                body.extend_from_slice(format!("--{boundary}--\r\n").as_bytes());
                let mut h = HeaderMap::new();
                h.insert(
                    reqwest::header::CONTENT_TYPE,
                    HeaderValue::from_str(&format!("multipart/related; boundary={boundary}"))?,
                );
                client
                    .request(Method::POST, "/remote.php/dav/bulk", h, Some(body))
                    .await?
            }
            Op::OcsUserQuota { user, quota } => {
                client
                    .ocs_user_update(&interpolate(user, vars), "quota", &interpolate(quota, vars))
                    .await?
            }
        };
        results.push(OpResult {
            op: describe(op),
            status: resp.status().as_u16(),
            body: None,
            body_bytes: None,
            propfind_shape: None,
            elapsed: start.elapsed(),
        });
    }
    Ok(results)
}

/// Replay the scenario's main ops against one instance.
pub async fn run(
    client: &NextcloudClient,
    sc: &Scenario,
    vars: &mut HashMap<String, String>,
) -> Result<Vec<OpResult>> {
    run_ops(client, &sc.ops, vars).await
}

/// Replay the scenario's cleanup ops (after the after-snapshot; not diffed).
/// All cleanup ops are attempted even if earlier ones fail; errors accumulate.
pub async fn run_cleanup(
    client: &NextcloudClient,
    sc: &Scenario,
    vars: &HashMap<String, String>,
) -> Result<()> {
    let mut errors = Vec::new();
    let mut vars_mut = vars.clone();
    for op in &sc.cleanup {
        if let Err(e) = run_ops(client, std::slice::from_ref(op), &mut vars_mut).await {
            errors.push(format!("{}: {e:#}", describe(op)));
        }
    }
    if errors.is_empty() {
        Ok(())
    } else {
        bail!("cleanup failed: {}", errors.join("; "))
    }
}

#[cfg(test)]
mod tests {
    use super::{propfind_shape, PropfindShape, Scenario};

    #[test]
    fn shape_counts_responses_and_hrefs() {
        // Two children + the root; a nested share-types prop must not confuse
        // the href scan.
        let body = r#"<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/files/admin/</d:href>
    <d:propstat><d:prop><d:getetag>"abc"</d:getetag></d:prop></d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/files/admin/Media/</d:href>
    <d:propstat><d:prop><oc:share-types><oc:share-type>1</oc:share-type></oc:share-types></d:prop></d:propstat>
  </d:response>
</d:multistatus>"#;
        let s = propfind_shape(body);
        assert_eq!(s.responses, 2, "closing tags must not double-count");
        assert_eq!(
            s.hrefs,
            vec![
                "/remote.php/dav/files/admin/",
                "/remote.php/dav/files/admin/Media/"
            ],
            "hrefs must be the opening-tag values only"
        );
    }

    #[test]
    fn shape_prop_sets_with_nested_values() {
        // Two propstats (200 + 404), a self-closing prop, and nested value
        // elements (sharee details) that must not count as props.
        let body = r#"<d:multistatus xmlns:d="DAV:" xmlns:nc="http://nextcloud.org/ns">
  <d:response>
    <d:href>/a</d:href>
    <d:propstat><d:prop><d:getetag>"x"</d:getetag><nc:sharees><nc:sharee><nc:id>1</nc:id><nc:type>user</nc:type></nc:sharee></nc:sharees><nc:system-tags/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat>
    <d:propstat><d:prop><nc:lock/><d:getcontentlength></d:getcontentlength></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat>
  </d:response>
</d:multistatus>"#;
        let s = propfind_shape(body);
        assert_eq!(s.responses, 1);
        let (p200, p404) = s.props.get("/a").expect("node props");
        let mut p200 = p200.clone();
        p200.sort();
        let mut p404 = p404.clone();
        p404.sort();
        if p200 != vec!["getetag", "sharees", "system-tags"] || p404 != vec!["getcontentlength", "lock"] {
            panic!("props map: {:#?}", s.props);
        }
    }

    #[test]
    fn shape_empty_or_error_body() {
        // A 401/500 body (or a truncated listing) has no multistatus shape.
        assert_eq!(propfind_shape("Unauthorized"), PropfindShape::default());
        assert_eq!(propfind_shape(""), PropfindShape::default());
    }

    #[test]
    fn shape_ignores_other_prop_elements() {
        // getetag values contain quotes and slashes; they must not leak into
        // the href set.
        let body = r#"<d:multistatus xmlns:d="DAV:"><d:response><d:href>/a</d:href><d:propstat><d:prop><d:getetag>"a/b"</d:getetag><d:getlastmodified>Fri, 14 Aug 2026 07:04:28 GMT</d:getlastmodified></d:prop></d:propstat></d:response></d:multistatus>"#;
        let s = propfind_shape(body);
        assert_eq!(s.responses, 1);
        assert_eq!(s.hrefs, vec!["/a"]);
    }

    #[test]
    fn scenario_28_move_versioned_file_parses() {
        let p = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/scenarios/28_move_versioned_file.yaml"
        );
        let sc = Scenario::load(p).unwrap();
        assert_eq!(sc.name, "28_move_versioned_file");
        assert_eq!(sc.ops.len(), 3, "put, put, move");
        assert_eq!(sc.cleanup.len(), 1, "delete the moved file");
        assert!(sc.stable_overrides.contains(&"oc_filecache.mtime".to_string()));
    }

    #[test]
    fn scenario_29_copy_versioned_file_parses() {
        let p = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/scenarios/29_copy_versioned_file.yaml"
        );
        let sc = Scenario::load(p).unwrap();
        assert_eq!(sc.name, "29_copy_versioned_file");
        assert_eq!(sc.ops.len(), 3, "put, put, copy");
        assert_eq!(sc.cleanup.len(), 2, "delete src + copied");
        assert!(sc.stable_overrides.contains(&"oc_filecache.mtime".to_string()));
    }
}
